[package]
name = "alass-ffi-macros"
version = "0.1.0"
authors = ["Weston Siegenthaler <westons+github@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.13", features = ["full"] }
quote = "1.0.2"

[dev-dependencies]
log = "0.4.8"
